# Generated by Django 4.1.6 on 2023-02-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPO', '0002_user_member_user_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_member',
            name='json',
            field=models.TextField(default='Individual'),
        ),
        migrations.AddField(
            model_name='user_organizer',
            name='json',
            field=models.TextField(default='Individual'),
        ),
    ]
