# Generated by Django 4.1.6 on 2023-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPO', '0005_rename_json_user_organizer_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_organizer',
            old_name='json_data',
            new_name='json',
        ),
        migrations.AddField(
            model_name='organizer_project',
            name='json',
            field=models.TextField(default='Individual'),
        ),
    ]
