# Generated by Django 4.1.6 on 2023-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPO', '0006_rename_json_data_user_organizer_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer_project',
            name='json_data',
            field=models.TextField(default='Individual'),
        ),
    ]
