# Generated by Django 4.1.6 on 2023-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPO', '0007_organizer_project_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_organizer', models.CharField(max_length=255)),
                ('title', models.TextField(default='')),
                ('short_description', models.TextField(default='')),
                ('big_description', models.TextField(default='')),
                ('category_vpo', models.TextField(default='')),
                ('category_help', models.TextField(default='')),
                ('data_create', models.DateTimeField(default='')),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
    ]
