# Generated by Django 4.1.6 on 2023-02-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPO', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='big_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_help',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_vpo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_create',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='permission',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
